In [1]:
import math
import numpy as np
from itertools import permutations
from collections import *
from functools import lru_cache

In [2]:
def generate_matrix(m, n):
    return np.random.randint(0, 10, size=(m, n))


def brute_force(grid: list[list[int]]) -> int:
    m, n = len(grid) - 1, len(grid[0]) - 1  # (m, n) = (nrow, ncolumn)
    D, R = (1, 0), (0, 1)
    moves = m * (D,) + (R,) * n
    path_way = set(permutations(moves, m + n))
    print(len(path_way))

    # 'D': (1, 0) matrix[i+1][j+0]
    # 'R': (0, 1) matrix[i+0][j+1]

    path_sum = ()
    for path in path_way:
        i = j = 0  # Starting from top left
        unit_sum = grid[i][j]
        for (di, dj) in path:
            i, j = i + di, j + dj
            unit_sum += grid[i][j]
        path_sum += (unit_sum,)

    return min(path_sum)


def min_path_sum(grid: list[list[int]]) -> int:
    min_sum = []
    m, n = len(grid), len(grid[0])
    counts = np.zeros((m, n), dtype=int)
    
    def dfs(i, j, running_sum):
        running_sum += grid[i][j]
        
        if (i + 1, j + 1) == (m, n):
            min_sum.append(running_sum)
            return
        if i + 1 < m and j < n:
            counts[(i + 1, j)] += 1
            dfs(i + 1, j, running_sum)
        if i < m and j + 1 < n:
            counts[(i, j + 1)] += 1
            dfs(i, j + 1, running_sum)
    
    dfs(0, 0, 0)
    print(counts)
    print(counts.sum())
    return min(min_sum)

def bfO(m, n):
    m, n = m - 1, n - 1
    return math.comb(m + n, n)

@lru_cache
def f(n):
    if n == 0 or n == 1:
        return n
    else:
        return f(n - 1) + f(n - 2)

@lru_cache
def g(i: int, j: int) -> int:
    match (i, j):
        case (0, 0):
            return 0
        case (_, 0) | (0, _):
            return 1
        case _:
            return g(i - 1, j) + g(i, j - 1)

def mpsO(m: int, n: int) -> int:
    c = 0
    for i in range(m):
        for j in range(n):
            c += g(i, j)
    
    return c

In [12]:
m, n = 4, 4
matrix = generate_matrix(m, n)
# print(matrix)

In [13]:
min_path_sum(matrix)

[[ 0  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]]
68


13

In [14]:
print(np.array([[f"{i}{j}" for j in range(n)] for i in range(m)]))

[['00' '01' '02' '03']
 ['10' '11' '12' '13']
 ['20' '21' '22' '23']
 ['30' '31' '32' '33']]


In [27]:
o, p = 6, 6
print(f"brute_force: {bfO(o, p)}")
print(f"depth-first: {mpsO(o, p)}")
print(f"lru_cache  : {o * p}")

brute_force: 252
depth-first: 922
lru_cache  : 36
