In [1]:
import numpy as np
import pandas as pd

In [2]:
def nodones(start, stop):
    count = 0
    for i in range(start, stop+1):
        count += str(i).count('1')
    return count
def nodarr(ar):
    for row in ar:
        count = 0
        for val in row:
            count += str(val).count('1')
        print(f'{row}\t\t -> {count}')

def nodstep(doto, upto):
    for i in range(doto, upto+1, 10):
        count = 0
        for j in range(i):
            count += str(j).count('1')
        print(f'[0, {i-1:>5}]\t -> {count}')

def nodig(n, d):
    c = 0
    d = str(d)
    for i in range(n + 1):
        c += str(i).count(d)
    return c

In [3]:
arr = np.arange(100).reshape(10, 10)

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
nodarr(arr)

[0 1 2 3 4 5 6 7 8 9]		 -> 1
[10 11 12 13 14 15 16 17 18 19]		 -> 11
[20 21 22 23 24 25 26 27 28 29]		 -> 1
[30 31 32 33 34 35 36 37 38 39]		 -> 1
[40 41 42 43 44 45 46 47 48 49]		 -> 1
[50 51 52 53 54 55 56 57 58 59]		 -> 1
[60 61 62 63 64 65 66 67 68 69]		 -> 1
[70 71 72 73 74 75 76 77 78 79]		 -> 1
[80 81 82 83 84 85 86 87 88 89]		 -> 1
[90 91 92 93 94 95 96 97 98 99]		 -> 1


In [6]:
nodarr(arr + 100)

[100 101 102 103 104 105 106 107 108 109]		 -> 11
[110 111 112 113 114 115 116 117 118 119]		 -> 21
[120 121 122 123 124 125 126 127 128 129]		 -> 11
[130 131 132 133 134 135 136 137 138 139]		 -> 11
[140 141 142 143 144 145 146 147 148 149]		 -> 11
[150 151 152 153 154 155 156 157 158 159]		 -> 11
[160 161 162 163 164 165 166 167 168 169]		 -> 11
[170 171 172 173 174 175 176 177 178 179]		 -> 11
[180 181 182 183 184 185 186 187 188 189]		 -> 11
[190 191 192 193 194 195 196 197 198 199]		 -> 11


In [7]:
nodarr(arr + 200)

[200 201 202 203 204 205 206 207 208 209]		 -> 1
[210 211 212 213 214 215 216 217 218 219]		 -> 11
[220 221 222 223 224 225 226 227 228 229]		 -> 1
[230 231 232 233 234 235 236 237 238 239]		 -> 1
[240 241 242 243 244 245 246 247 248 249]		 -> 1
[250 251 252 253 254 255 256 257 258 259]		 -> 1
[260 261 262 263 264 265 266 267 268 269]		 -> 1
[270 271 272 273 274 275 276 277 278 279]		 -> 1
[280 281 282 283 284 285 286 287 288 289]		 -> 1
[290 291 292 293 294 295 296 297 298 299]		 -> 1


In [8]:
nodarr(arr + 300)

[300 301 302 303 304 305 306 307 308 309]		 -> 1
[310 311 312 313 314 315 316 317 318 319]		 -> 11
[320 321 322 323 324 325 326 327 328 329]		 -> 1
[330 331 332 333 334 335 336 337 338 339]		 -> 1
[340 341 342 343 344 345 346 347 348 349]		 -> 1
[350 351 352 353 354 355 356 357 358 359]		 -> 1
[360 361 362 363 364 365 366 367 368 369]		 -> 1
[370 371 372 373 374 375 376 377 378 379]		 -> 1
[380 381 382 383 384 385 386 387 388 389]		 -> 1
[390 391 392 393 394 395 396 397 398 399]		 -> 1


In [9]:
(nodones(0, 9), nodones(0, 19), nodones(0, 29), nodones(0, 39), nodones(0, 49), nodones(0, 59), nodones(0, 69), nodones(0, 79), nodones(0, 89), nodones(0, 99))

(1, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [10]:
(nodones(0, 109), nodones(0, 119), nodones(0, 129), nodones(0, 139), nodones(0, 149), nodones(0, 159), nodones(0, 169), nodones(0, 179), nodones(0, 189), nodones(0, 199))

(31, 52, 63, 74, 85, 96, 107, 118, 129, 140)

In [11]:
nodstep(10, 100)

[0,     9]	 -> 1
[0,    19]	 -> 12
[0,    29]	 -> 13
[0,    39]	 -> 14
[0,    49]	 -> 15
[0,    59]	 -> 16
[0,    69]	 -> 17
[0,    79]	 -> 18
[0,    89]	 -> 19
[0,    99]	 -> 20


In [12]:
nodstep(110, 200)

[0,   109]	 -> 31
[0,   119]	 -> 52
[0,   129]	 -> 63
[0,   139]	 -> 74
[0,   149]	 -> 85
[0,   159]	 -> 96
[0,   169]	 -> 107
[0,   179]	 -> 118
[0,   189]	 -> 129
[0,   199]	 -> 140


In [13]:
nodstep(210, 300)

[0,   209]	 -> 141
[0,   219]	 -> 152
[0,   229]	 -> 153
[0,   239]	 -> 154
[0,   249]	 -> 155
[0,   259]	 -> 156
[0,   269]	 -> 157
[0,   279]	 -> 158
[0,   289]	 -> 159
[0,   299]	 -> 160


In [14]:
nodstep(310, 400)

[0,   309]	 -> 161
[0,   319]	 -> 172
[0,   329]	 -> 173
[0,   339]	 -> 174
[0,   349]	 -> 175
[0,   359]	 -> 176
[0,   369]	 -> 177
[0,   379]	 -> 178
[0,   389]	 -> 179
[0,   399]	 -> 180


In [15]:
nodstep(410, 500)

[0,   409]	 -> 181
[0,   419]	 -> 192
[0,   429]	 -> 193
[0,   439]	 -> 194
[0,   449]	 -> 195
[0,   459]	 -> 196
[0,   469]	 -> 197
[0,   479]	 -> 198
[0,   489]	 -> 199
[0,   499]	 -> 200


In [16]:
nodstep(1100, 1200)

[0,  1099]	 -> 420
[0,  1109]	 -> 441
[0,  1119]	 -> 472
[0,  1129]	 -> 493
[0,  1139]	 -> 514
[0,  1149]	 -> 535
[0,  1159]	 -> 556
[0,  1169]	 -> 577
[0,  1179]	 -> 598
[0,  1189]	 -> 619
[0,  1199]	 -> 640


In [17]:
nodones(10, 20)

11

In [18]:
nodones(100, 200)

120

In [19]:
nodones(1000, 2000)

1300

In [20]:
nodones(10000, 20000)

14000

In [26]:
np.arange(0, 1000).reshape(100, 10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [22]:
nodones(0, 111)

36

In [23]:
nodig(222, 2)

69