In [4]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("dark_background")

In [34]:
def gen(m, n):
    return np.arange(1, m * n + 1).reshape(m, n)

def O(m, n):
    mx = (m * (m + 1)) // 2
    nx = (n * (n + 1)) // 2
    return mx * nx

def submats(matrix):
    m, n = matrix.shape
    ans = []
    for I in range(1, m + 1):
        for J in range(1, n + 1):
            print(f"Matrix {I}x{J}")
            for i in range(m - I + 1):
                for j in range(n - J + 1):
                    print(matrix[i:i + I, j:j + J])
#                     ans.append(matrix[i:i + I, j:j + J])
    return ans

def Od(matrix):
    m, n = matrix.shape
    count = 0
    for I in range(1, m + 1):
        for J in range(1, n + 1):
            for i in range(m - I + 1):
                for j in range(n - J + 1):
                    count += matrix[i:i + I, j:j + J].size
    return count

def Oe(matrix):
    m, n = matrix.shape
    c = 0
    for I in range(1, m + 1):
        for J in range(1, n + 1):
            c += (m - I + 1) * (n - J + 1) * I * J
    
    return c

def membership(m, n):
    matrix = gen(m, n)
    submatrices = submats(matrix)
    ans = np.zeros((m, n), dtype=int)
    for i in range(m):
        for j in range(n):
            for submatrix in submatrices:
                if matrix[i, j] in submatrix:
                    ans[i, j] += 1
    
    return ans

In [6]:
print(gen(2, 2))

[[1 2]
 [3 4]]


<pre>
Matrix 2x2 = 9 (submats)
1x1 - 4
1x2 - 2
2x1 - 2
2x2 - 1
</pre>

In [7]:
print(gen(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<pre>
Matrix 3x3 = 36 (submats)
1x1 - 9
1x2 - 6
1x3 - 3
2x1 - 6
2x2 - 4
2x3 - 2
3x1 - 3
3x2 - 2
3x3 - 1
</pre>

In [8]:
print(gen(2, 3))

[[1 2 3]
 [4 5 6]]


<pre>
Matrix 2x3 = 18 (submats)
1x1 - 6
1x2 - 4
1x3 - 2
2x1 - 3
2x2 - 2
2x3 - 1
</pre>

In [9]:
9+6+3+6+4+2+3+2+1

36

In [10]:
print(gen(4, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


<pre>
Matrix 4x4 = 100 (submats)
1x1 - 16
1x2 - 12
1x3 - 8
1x4 - 4
2x1 - 12
2x2 - 9
2x3 - 6
2x4 - 3
3x1 - 8
3x2 - 6
3x3 - 4
3x4 - 2
4x1 - 4
4x2 - 3
4x3 - 2
4x4 - 1
</pre>

In [11]:
16+12+8+4+12+9+6+3+8+6+4+2+4+3+2+1

100

In [12]:
a = 3
(3*a)*(3*a)

81

<pre>
Matrix 3x3
[1 2 3]     [ 9 12  9]
[4 5 6]     [12 16 12]
[7 8 9]     [ 9 12  9]
</pre>

In [13]:
print(*submats(gen(3, 3)), sep='\n')

Matrix 1x1
[[1]]
[[2]]
[[3]]
[[4]]
[[5]]
[[6]]
[[7]]
[[8]]
[[9]]
Matrix 1x2
[[1 2]]
[[2 3]]
[[4 5]]
[[5 6]]
[[7 8]]
[[8 9]]
Matrix 1x3
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Matrix 2x1
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]
[[4]
 [7]]
[[5]
 [8]]
[[6]
 [9]]
Matrix 2x2
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]
Matrix 2x3
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
Matrix 3x1
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]
Matrix 3x2
[[1 2]
 [4 5]
 [7 8]]
[[2 3]
 [5 6]
 [8 9]]
Matrix 3x3
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [14]:
d = {}
m, n = 3, 3
tmp = gen(m, n)
I, J = 1, 2
for i in range(m - I + 1):
    for j in range(n - J + 1):
        d[((i + 1, i + I), (j + 1, j + J))] = tmp[i:i + I, j:j + J].sum()
d

{((1, 1), (1, 2)): 3,
 ((1, 1), (2, 3)): 5,
 ((2, 2), (1, 2)): 9,
 ((2, 2), (2, 3)): 11,
 ((3, 3), (1, 2)): 15,
 ((3, 3), (2, 3)): 17}

<pre>
[1 2 3]
[4 5 6]
[7 8 9]
 </pre>

###### check with transitive property nature of start index and stop index

In [15]:
x = [1, 2, 3, 4, 5, 6]
y = [1, 4, 10, 20, 35, 56]

<pre>
1 x 4
2 x 3
3 x 2
4 x 1
</pre>

In [16]:
def dis1d(nums):
    n = len(nums)
    for i in range(1, n + 1):
        print(f"SubSeq: {1, i}")
        for j in range(n - i + 1):
            print(f"{j, i + j}   {nums[j:i + j]}")

In [17]:
dis1d(list(range(1, 6)))

SubSeq: (1, 1)
(0, 1)   [1]
(1, 2)   [2]
(2, 3)   [3]
(3, 4)   [4]
(4, 5)   [5]
SubSeq: (1, 2)
(0, 2)   [1, 2]
(1, 3)   [2, 3]
(2, 4)   [3, 4]
(3, 5)   [4, 5]
SubSeq: (1, 3)
(0, 3)   [1, 2, 3]
(1, 4)   [2, 3, 4]
(2, 5)   [3, 4, 5]
SubSeq: (1, 4)
(0, 4)   [1, 2, 3, 4]
(1, 5)   [2, 3, 4, 5]
SubSeq: (1, 5)
(0, 5)   [1, 2, 3, 4, 5]


<pre>
                [1, 2, 3, 4, 5]
</pre>

In [ ]:
n = 100
(n * (n + 1)) // 2

In [23]:
mat1 = gen(3, 3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
O(mat1)

100

In [ ]:
21 - 12 - 6 - 3

In [ ]:
12 + 6 + 3

In [19]:
mat2 = np.random.randint(-5, 6, size=(3, 3))

In [21]:
21 + 27 - 12

36

In [60]:
mat3 = gen(100, 100)

In [55]:
Oe(mat3) == Od(mat3)

True

In [61]:
O(*mat3.shape), Oe(mat3), Od(mat3)

(25502500, 29480890000, 29480890000)

In [59]:
(2371600 + 44100) * 50

120785000