In [2]:
import numpy as np

In [14]:
def similarity(matrix1, matrix2):
    m1, n1 = matrix1.shape
    m2, n2 = matrix2.shape
    count = 0
    for i in range(m1 + m2 - 1):
        for j in range(n1 + n2 - 1):
            count += 1
            print((i, j))
        print()
    
    print(count)

In [12]:
m1, n1 = 3, 3
m2, n2 = 3, 3

arr1 = np.random.randint(1, 10, (m1, n1))
arr2 = np.random.randint(1, 10, (m2, n2))

In [15]:
similarity(arr1, arr2)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)

(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)

(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)

(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)

(4, 0)
(4, 1)
(4, 2)
(4, 3)
(4, 4)

25


In [11]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(slice(1, 5))

slice(1, 5, None)


In [20]:
arr1[(0, 3), (0, 1)]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [23]:
arr1[(0, 2)]

4

In [ ]:
arr1.__getitem__()